### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JustTheSame** [ToView/qrcodecore#2]
关于：
QRCodeUtils. createWithLogo(String text, String logoPath)
输入文本内容，logo图片路径，返回生成带有logo的二维码图片的字节流。

我想请问这个输出字节流应该怎么使用？
应该怎么处理它？

**Comment by ToView** [comment]
你可以把这个字节流转换成File来使用。

**Comment by ToView** [comment]
` OutputStream outputStream = QRCodeUtils.createWithLogo("http://www.google.com", logoPath);
            ByteArrayOutputStream byteArrayOutputStream = (ByteArrayOutputStream) outputStream;
            File file = new File("E:\\img\\test.jpg");
            FileOutputStream outputStream1 = new FileOutputStream(file);
            outputStream1.write(byteArrayOutputStream.toByteArray());`
